language: node_js
node_js: "node"
dist: trusty
sudo: false

script: npm run build

deploy:
  provider: pages
  edge:
    branch: pages-ivar-set
  local-dir: dist/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master